language: swift
osx_image: xcode8

before_install:
  - gem install xcpretty

script:
  - set -o pipefail && xcodebuild -project KataLoginLogOut.xcodeproj -scheme 'KataLoginLogOut' -destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -c