language: swift
osx_image: xcode8 

before_install:
  - gem install xcpretty

script:
  -set -o pipefail && xcodebuild -project KataLoginLogOut.xcodeproj -scheme 'KataLoginLogOut' build test | xcpretty -c